### ISSUE TITLE
MinArrayLength rule wrong writing

### ISSUE THREAD

**Issue by Paulymorph** [ITV/scala-pact#108]
There is a problem with writing the `ScalaPactMatchingRuleArrayMinLength`.

In the [specification](https://github.com/pact-foundation/pact-specification/tree/version-2#supported-matchers), the min type rule is defined like this: `{ "match": "type", "min": 2 }`. 
But scala-pact generates only `{"min": 2 }` for the rule and the providers just fail to check the rule correctly. 
The problem should be solved with a minor change in [this line](https://github.com/ITV/scala-pact/blob/222ecc579d8869a8e28c05f074f21e701b71a5e0/scalapact-scalatest/src/main/scala/com/itv/scalapact/ScalaPactContractWriter.scala#L115).

I would try to PR a fix, when I have an opportunity.

**Comment by davesmith00000** [comment]
Thank you for providing the link, excitingly we also don't have a 'max' (which also means that there is no test for that in the official test suite!). Good find.
A good summary of the bug, I must caution that the Pact-Spec is really flakey and inconsistent. In this case it looks like (as you said) it's just the way we write the spec out, so hopefully you'll be fine.
I was planning to work on Scala-Pact today. I'll start somewhere else but if you'd like me to have a look at this then please drop a message to that effect on here.
