### ISSUE TITLE
Please support authorization with a bearer token

### ISSUE THREAD

**Issue by bethesque** [ITV/scala-pact#140]
Hey Dave!

Pactflow now supports authenticating with a bearer token (`Authorization: Bearer TOKEN` header). Could you add this as an option to the scala impl? Let me know if you have any questions.

Also coming soon will be some new endpoints to support "pending pacts" which will allow new pacts to be verified in "pending" mode so they don't break the provider CI. It's going to be awesome!

Thanks!

**Comment by dantb** [comment]
Hi Beth,

I'll have a bash at implementing this. What's the process for creating a token? Feel free to point me to any docs - I can't see this mentioned in the pact broker docs so is this is a pactflow specific feature?

Cheers,
Dan

**Comment by bethesque** [comment]
Hey Dan. Yes, this is Pactflow specific. If you grab a free account at pactflow.io you can use it for testing.

**Comment by dantb** [comment]
Added in PR #141 - will close this issue when that change is released

**Comment by dantb** [comment]
Released PR #141 in version 2.3.9

**Comment by bethesque** [comment]
Thanks!
