### ISSUE TITLE
Implement "wip pacts"

### ISSUE THREAD

**Issue by bethesque** [ITV/scala-pact#161]
See https://github.com/pact-foundation/pact_broker/issues/338

**Comment by jbwheatley** [comment]
Hey @bethesque, I'm working on adding this feature to scala-pact, but I'm wondering if you could help suggest a sensible strategy for writing some automated tests for it?

**Comment by bethesque** [comment]
The best thing you could do is write a pact for it that the broker verifies. Like this one here between the broker and the broker client https://github.com/pact-foundation/pact_broker-client/blob/master/spec/pacts/pact_broker_client-pact_broker.json

**Comment by bethesque** [comment]
The logic of "what makes a pact WIP" is something that the client should not be aware of however, as this has changed a few times already! It just needs to know that there are WIP pacts and that it should use the right field for it.
