### ISSUE TITLE
Pact verification does not publish provider tags

### ISSUE THREAD

**Issue by solarmosaic-kflorence** [ITV/scala-pact#207]
I am using `pactBrokerWithVersionSelectors` with `publishResultsEnabled`. I expected this to publish the results along with the provided `providerVersionTags`, but it does not. This seems to deviate from the consumer pact publishing behavior, which publishes the pacts along with the tags. This means that currently for my CI builds, the consumer pacts are correctly tagged with the branch, but the provider verification results are not.

https://docs.pact.io/pact_broker/tags/#when-publishing-verification-results

**Comment by jbwheatley** [comment]
Good spot. Nice to see someone is trying to use scala-pact for some of the less vanilla pact features than we have! Creating an issue to add this feature

**Comment by solarmosaic-kflorence** [comment]
@jbwheatley I opened a work in progress PR as a starting point. Feel free to take that over if you have time as it will take me awhile to figure out how to test it.

**Comment by jbwheatley** [comment]
@solarmosaic-kflorence I've got some time, I'll hop on your branch and try and get things working
