### ISSUE TITLE
Add set up and tear down functionality to provider states

### ISSUE THREAD

**Issue by itsDanOades** [ITV/scala-pact#27]
Current provider state functions will only be called before a pact is executed, Ruby pact supports the concept of set up and tear downs when specifying a provider state as well as global and default provider states.

See:
https://github.com/realestate-com-au/pact/wiki/Provider-states

**Comment by davesmith00000** [comment]
Let me know if you want me to look into this @itsDanOades

**Comment by davesmith00000** [comment]
This can now be done is you use the pactVerify test suites. Not quite what you were after but it might help?

**Comment by davesmith00000** [comment]
I think some of this will also get addressed further with Pact V3 support. Closing for now. Recommended approach is to use the verification test suite.
