### ISSUE TITLE
Fail the test if the provider state fails

### ISSUE THREAD

**Issue by itsDanOades** [ITV/scala-pact#28]
When a provider state fails or returns false a warning is sent but does not fail the test. It would aid debugging the pact if it is obvious that the set up failed rather than the test execution.

`providerStates := Seq(
  ("The user with the ID SOME_ID exists", (key: String) => {
   false
  })
)`

**Comment by davesmith00000** [comment]
Let me know if you want me to look into this @itsDanOades

**Comment by davesmith00000** [comment]
Merged into master, will go out with the next release.
