### ISSUE TITLE
what's the default path of pact files when call pact-verify

### ISSUE THREAD

**Issue by notyy** [ITV/scala-pact#32]
hi,

I put pact files in project top level pact folder(same level as src).  when I set --source explicitly, 
`sbt "pact-verify --host localhost --protocol http --port 1234 --source pacts"`
it works. 

if I just call sbt pact-verify, it only says: 
> Verifying against 'localhost', port '1234'

then nothing happened.

I also tried "delivered_pacts" folder, as examples, it doesn't work.

**Comment by davesmith00000** [comment]
Hello!

`sbt "pact-verify --source delivered_pacts"` should work in the root of your project assuming delivered_pacts is in the same folder as your build.sbt file? 

If you specify `--source <path>` then you should see a console output saying:
```
Attempting to use local pact files at: <path>
```

The next part may not be obvious, it is in the docs but maybe could be clearer (http://io.itv.com/scala-pact/basics/sbt-commands-and-tasks.html#verifying-with-pact-broker-during-a-ci-build): if you don't specify a local `--source`, then it attempts to connect to pact broker and goes looking in your SBT files for the settings, and if it can't find them then it uses a bunch of empty values which *should* fail it's internal validation and cause an error? Hopefully? :-)

If that's not what you're seeing I'd love to see a screenshot or bug reproduction description and I will fix it!

**Comment by notyy** [comment]
that solved my question, thanks~
