### ISSUE TITLE
A large suite of tests fails with 'error writing to server'

### ISSUE THREAD

**Issue by BenParker22** [ITV/scala-pact#35]
I have a large suite of Pact tests (22 tests to be precise) that each utilises 'forgePact' With test number 22 failing, and any further tests past that also fail.

The response given by the mock is 500 'Error writing to server'
Changing the order of tests doesn't change this, whatever test is executed 22nd has this 500 response code from the mock

**Comment by davesmith00000** [comment]
Created a pull request with you as a reviewer:
https://github.com/ITV/scala-pact/pull/36

**Comment by davesmith00000** [comment]
Will go out in the next release.
