### ISSUE TITLE
Suggestion: summarize results after pact-verify

### ISSUE THREAD

**Issue by BenParker22** [ITV/scala-pact#42]
It would be useful to get a summary after running pact-verifiy that tells you how many tests passed/failed/cancelled like sbt does:
![screen shot 2017-01-12 at 10 01 29](https://cloud.githubusercontent.com/assets/13197669/21885098/21017a62-d8ae-11e6-9065-8e2d64db8cd7.png)

**Comment by davesmith00000** [comment]
Sounds like you're volunteering to do a PR Ben? ;-)

**Comment by davesmith00000** [comment]
I'd added the 'good first issue' label hesitantly. This is quite an easy change (I think...), but it's in the thick of the verification results logic so will require a bit of reading.

Here for example, we're already picking up a failure count based on the outcome of the results:
https://github.com/ITV/scala-pact/blob/fdff5d30aaf0c4ba3fea56ab147603744a114b1e/scalapact-core/src/main/scala/com/itv/scalapactcore/verifier/Verifier.scala#L64

**Comment by davesmith00000** [comment]
This has been done!
