### ISSUE TITLE
provider_state vs. providerState

### ISSUE THREAD

**Issue by davesmith00000** [ITV/scala-pact#44]
It seems that most other implementations use `provider_state` rather than `providerState` when writing the pact files.

We need to confirm this is true (I can't find any docs, our evidence is just stuff we've seen in the wild). I'll ask on the pact-dev group.

The fix (if true) is to adapt the ScalaPactReader class to accept both formats, and then change the writer to only emit `provider_state`.

**Comment by itsDanOades** [comment]
Confirmed by Beth that it should be providerState, however some pact libs output provider_state. 

https://github.com/ITV/scala-pact/pull/45
