### ISSUE TITLE
Support multiple pact brokers

### ISSUE THREAD

**Issue by davesmith00000** [ITV/scala-pact#49]

**Comment by davesmith00000** [comment]
Hello @squinker, I nearly picked this up yesterday. :-)

Delighted to have help though, do let me know if you need anything.

My only requirement is that this isn't a breaking change for existing users - other than that I'm excited to see what you come up with.

**Comment by squinker** [comment]
I'll have to unassign myself from this due to lack of free time in the foreseeable future :(  (I don't want to block others that might want to work on it). Soz

**Comment by davesmith00000** [comment]
No worries buddy. I've been out of action this month too but I'm hoping to get back onto this stuff soon!

**Comment by davesmith00000** [comment]
Should be in the next release.
