### ISSUE TITLE
Doesn't work with chunked requests

### ISSUE THREAD

**Issue by yasuba** [ITV/scala-pact#50]
.withBackendConfig(BackendConfig(
        allowChunkedRequestBody = false
      ))

**Comment by davesmith00000** [comment]
For my own memory: This was using the RosHTTP library which chunks POST request bodies by default. If it matters this was also an XML request we were testing.
https://github.com/hmil/RosHTTP

**Comment by davesmith00000** [comment]
Will be in next release.
