### ISSUE TITLE
Allow ports for pact broker address

### ISSUE THREAD

**Issue by rustige** [ITV/scala-pact#56]
Please allow broker access via a defined port.

- I got a broker running on port 5000.
- `pactBrokerAddress := "http://localhost:5000"` inside build.sbt

It throws the following erro on `sbt pact-publish`:
> Pact broker address does not appear to be valid, should be of form: http://my.broker-address.com

**Comment by davesmith00000** [comment]
Oh good catch! I'll check it out as soon as I can. Thanks!

**Comment by davesmith00000** [comment]
This has been fixed and will be in the next release.

**Comment by davesmith00000** [comment]
Hi @rustige, can you please verify this works in version 2.1.3?

**Comment by rustige** [comment]
Yes, it works with 2.1.3.
Thank you very much.

**Comment by davesmith00000** [comment]
Glad we could help! Thanks for bringing the issue to our attention.
