### ISSUE TITLE
Add configurable versions to pact-verify

### ISSUE THREAD

**Issue by itsDanOades** [ITV/scala-pact#6]
The sbt pact-verify settings will only pull the latest pacts from the broker, can this be made configurable in pact.sbt to allow specific pact versions to pulled by the provider.

consumerNames := Seq("User Domain CI", "iOS")
versionedConsumerNames := Seq(("Consumer 1" , "1.0.0"), ("Consumer 2", "2.0.0"))

**Comment by davesmith00000** [comment]
Merged to master, awaiting release. Trying to get to the bottom of Naree's issue first if I can but I won't let it hold this up much longer. Sorry for the delay.

**Comment by davesmith00000** [comment]
Released
