### ISSUE TITLE
Failure to download from the pact broker should fail the test

### ISSUE THREAD

**Issue by itsDanOades** [ITV/scala-pact#60]
Running pact-verify against a pact broker url does not fail the test if the pact is not present or times out loading from the broker.

Should it be a hard failure?

**Comment by davesmith00000** [comment]
Yes I think so. I think you could argue it either way but I think a hard failure sounds better than a silent one. Especially in a CI environment.

**Comment by davesmith00000** [comment]
Did we fix this? Need to check.

**Comment by itsDanOades** [comment]
@davesmith00000 nope, still an issue

**Comment by davesmith00000** [comment]
Right you are, I'll have a look.

**Comment by davesmith00000** [comment]
Should be fixed for old branch in `2.2.5`. Needs to be ported across the the main branch though, next week I hope. Care to verify @itsDanOades ?

**Comment by davesmith00000** [comment]
The 2.3.x branch will also exit with a non-zero code if zero verifications were attempted.

**Comment by davesmith00000** [comment]
Released in `2.2.5` and `2.3.2`.
