### ISSUE TITLE
SBT 1.0.x Compatibility

### ISSUE THREAD

**Issue by davesmith00000** [ITV/scala-pact#69]
If this PR ever gets merged - all the problems are solved:
https://github.com/lucidsoftware/sbt-cross/pull/10

Otherwise, the work is to re-work all the cross publishing...

**Comment by Bhudjo** [comment]
I saw that @rtimush published https://github.com/rtimush/sbt-scala-crossproject

Would that help in releasing a version with sbt 1.x compatibility?

**Comment by davesmith00000** [comment]
Thanks, I had started looking at that as an alternative. I also have an SBT 1.x branch which fixes a multitude of old sins so I may just go that route on the assumption that most people will be upgrading anyway, and the old versions will live on in the meantime... but I haven't fully decided! :-)

**Comment by davesmith00000** [comment]
SBT 1.x is supported with version 2.3.0-RC1.
