### ISSUE TITLE
Resource [logback.xml] occurs multiple times on the classpath

### ISSUE THREAD

**Issue by cjwebb** [ITV/scala-pact#82]
Hello! I currently have an annoying warning message when running tests for a Play application that uses scalapact, due to scalapact-scalatest having a `logback.xml` included in the JAR. This gets added to the classpath alongside the application's logback.xml:

```
12:14:29,013 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
12:14:29,014 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/cwebb/.ivy2/cache/com.itv/scalapact-scalatest_2.12/jars/scalapact-scalatest_2.12-2.2.3.jar!/logback.xml]
```

A brief google suggests that libraries should not publish logging configuration, as a general rule. Do you agree with this? Can we remove it from the published jar, or would you prefer it to remain?

**Comment by davesmith00000** [comment]
Think I'll file that one under "Whoops!" yes agreed we should get rid of it.
