### ISSUE TITLE
Support Play

### ISSUE THREAD

**Issue by erip** [ITV/scala-pact#90]
This seems like it should be reasonable. Given Play and Lagom for service development, it would be nice if play-json were supported.

**Comment by davesmith00000** [comment]
Hi!

Building a play-json version of the json modules should be entirely doable - PR's welcome! ;-)

That said, the point of the modules is to help people work around dependency hell. Dependency hell occurs when your project is using the same library as Scala-Pact but at a different version, and one of them is evicted. For example, if your project used Circe 0.8, but I'd baked in Circe 0.9, you'd have a problem. When all the libraries are completely different, you should have no issues. Meaning that you can build your service in Play with Play-Json, say, while instructing Scala-Pact to use Http4s with Circe and that should be just fine. You won't need to use Circe or Http4s yourself, it's just used in the background.

If you've tried it and found an issue could you please let me know what happened? Thanks!

**Comment by davesmith00000** [comment]
Closing issue as I believe the basic requirement is already met, in that you should be able to use Scala-Pact with Play.
