### ISSUE TITLE
Client request timeout

### ISSUE THREAD

**Issue by e1ywka** [ITV/scala-pact#92]
Hello

I am using scala-pact on provider side.
```
   "com.itv"       %% "scalapact-circe-0-9"     % "2.2.3" % "test",
    "com.itv"       %% "scalapact-http4s-0-18-0" % "2.2.3" % "test",
    "com.itv"       %% "scalapact-scalatest"     % "2.2.3" % "test"
```
We set up privder before test and then verify it like this
```
verifyPact
        .withPactSource(loadFromLocal(pactFilePath))
        .noSetupRequired
        .runVerificationAgainst("localhost", 8194, 3 seconds)
```
But sometimes we get an error on the first checked pact
```Error in response: Client request timeout after 1666 milliseconds```

I thought it is some default timeout of http4s lib. How am I able to configure all suitable timeouts?

**Comment by e1ywka** [comment]
Please look at com.itv.scalapact.shared.http.ScalaPactHttpClient:38
There is a hard coded value of client timeout.

**Comment by davesmith00000** [comment]
You're on this project board. I think it's time I did one last 2.11 release (it's a massive effort). https://github.com/ITV/scala-pact/projects/2

**Comment by davesmith00000** [comment]
Change committed:
https://github.com/ITV/scala-pact/commit/398724c25518bedd96a98d846a5fe5596537c468

**Comment by davesmith00000** [comment]
Should be fixed now using version `2.2.5`, would you like to confirm @e1ywka ?

**Comment by e1ywka** [comment]
@davesmith00000, yes, that is it. Thank you!

**Comment by davesmith00000** [comment]
You're welcome - I've been meaning to fix that for ages! ;-)
