### ISSUE TITLE
External verification fails for provider with: Not a valid command: pact-verify

### ISSUE THREAD

**Issue by adam-pike-dunelm** [ITV/scala-pact#97]
**Description:**

I want to verify my pact file from my pact broker against my provider. But after following the guides I get an error.

**Steps:**

I have the following library dependencies in my build.sbt:

```
libraryDependencies ++= Seq(
  "com.itv"       %% "scalapact-circe-0-9"     % "2.2.3" % "test",
  "com.itv"       %% "scalapact-http4s-0-18-0" % "2.2.3" % "test",
  "com.itv"       %% "scalapact-scalatest"     % "2.2.3" % "test",
  "org.scalatest" %% "scalatest"               % "3.0.5" % "test"
)

```

I also have included my Pact broker details in the build.sbt:

```
pactBrokerAddress := "https://project.name.pact.dius.com.au/"
providerName := "provider.name"
consumerNames := Seq("consumer.name")

```

Then I run `sbt "pact-verify --host localhost --port 9600"` from the root directory where my build.sbt lives.

**Expected:** Pact should pulled down from Pact broker and run the verification.

**Actual:** Error

```
[warn] No sbt.version set in project/build.properties, base directory: /Users/my.user/workspace/
[info] Loading settings from idea.sbt ...
[info] Loading global plugins from /Users/my.user/workspace/.sbt/1.0/plugins
[info] Set current project to workspace (in build file:/Users/my.user/workspace/)
[error] Expected ID character
[error] Not a valid command: pact-verify
[error] Expected project ID
[error] Expected configuration
[error] Expected ':' (if selecting a configuration)
[error] Expected key
[error] Not a valid key: pact-verify
[error] pact-verify --host localhost --port 9600
```

**Comment by davesmith00000** [comment]
Hi Adam,

There is one of two things going on here I'd guess.

### Option 1 - No plugin
The `pact-verify` command comes from the plugin which you need to declare in your `plugins.sbt` file.

### Option 2 - Version misalignment

The clue is here:
`[warn] No sbt.version set in project/build.properties`

You haven't specified an SBT version to use, which means that you're either using your local version whatever it is, or if you're using a recent version of intellij it will have added an build.properties will with a new SBT 1.x version in it by default.

Why does this matter?

The version of Scala-Pact you've declared is `2.2.3` which is for SBT 0.13.x only. If you're using SBT 1.x then you won't be able to resolve the dependancy, you need `2.3.1` (I think it is). I used to massive changes between SBT 0.13.x and 1.x as an excuse to overhaul and deprecate a load of stuff to make maintenance easier.

Hope that helps,

Dave

**Comment by adam-pike-dunelm** [comment]
Hi Dave, 

I think you helped me find the smoking gun. 

I have the plugin declared - forgot to add that to the ticket sorry. But It looks like there's an sbt version issue - locally I'm running `sbt 1.0.2` and the project has  `sbt.version=0.13.15` set in the build.properties.

So it seems for some reason it's not picking up the project definition and and is breaking due to having the wrong libraries for the local version. 

I'll figure it out. :)

Thanks for the fast reply!
